<a href="https://colab.research.google.com/github/Lucifer12-18/ML-lab/blob/main/Principal_Component_Analysis_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import pandas as pd

# define a matrix
A = array([[2.5,2.4],
           [0.5,0.7],
           [2.2,2.9],
           [1.9,2.2],
           [3.1,3.0],
           [2.3,2.7],
           [2,1.6],
           [1,1.1],
           [1.5,1.6],
           [1.1,0.9]])
print(A)

[[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]


In [2]:
M = mean(A.T, axis=1)
print(M)

[1.81 1.91]


In [3]:
C = A - M
print(C)

[[ 0.69  0.49]
 [-1.31 -1.21]
 [ 0.39  0.99]
 [ 0.09  0.29]
 [ 1.29  1.09]
 [ 0.49  0.79]
 [ 0.19 -0.31]
 [-0.81 -0.81]
 [-0.31 -0.31]
 [-0.71 -1.01]]


#calculate covariance matrix of centered matrix.


In [4]:
V = cov(C.T)
print(V)

[[0.61655556 0.61544444]
 [0.61544444 0.71655556]]


In [5]:
#eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]
[0.0490834  1.28402771]


In [7]:
#project data
P = vectors.T.dot(C.T)
print(P.T)

[[-0.17511531 -0.82797019]
 [ 0.14285723  1.77758033]
 [ 0.38437499 -0.99219749]
 [ 0.13041721 -0.27421042]
 [-0.20949846 -1.67580142]
 [ 0.17528244 -0.9129491 ]
 [-0.3498247   0.09910944]
 [ 0.04641726  1.14457216]
 [ 0.01776463  0.43804614]
 [-0.16267529  1.22382056]]


In [8]:
from sklearn.decomposition import PCA

pca = PCA(2)
pca.fit_transform(A)
print(pca.components_)
print(pca.explained_variance_)
#transform data
B = pca.transform(A)
print(B)


[[-0.6778734  -0.73517866]
 [-0.73517866  0.6778734 ]]
[1.28402771 0.0490834 ]
[[-0.82797019 -0.17511531]
 [ 1.77758033  0.14285723]
 [-0.99219749  0.38437499]
 [-0.27421042  0.13041721]
 [-1.67580142 -0.20949846]
 [-0.9129491   0.17528244]
 [ 0.09910944 -0.3498247 ]
 [ 1.14457216  0.04641726]
 [ 0.43804614  0.01776463]
 [ 1.22382056 -0.16267529]]
